version: '3'
services:
  app: &app
    build: .
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/1
      REDIS_HOST: redis
    command: ['bundle', 'exec', 'rails', 's', '--port=3000', '--binding=0.0.0.0']
    ports:
      - 3000:3000
  sidekiq:
    <<: *app
    command: ['bundle', 'exec', 'sidekiq']
    ports: []
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dot
      POSTGRES_USER: dot
      POSTGRES_DB: dot
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  postgres: {}
  redis: {}
