---
pg_common: &pg_common
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  database: <%= ENV["DATABASE_DBNAME"] || "dot" %>
  username: <%= ENV["DATABASE_USERNAME"] || "dot" %>
  password: '<%= ENV["DATABASE_PASSWORD"] || "dot" %>'
  pool: <%= ENV['DATABASE_POOL_SIZE'] || "15" %>
development: *pg_common
test:
  <<: *pg_common
  database: <%= ENV["DATABASE_DBNAME"] || "dot_test" %>
staging: *pg_common
production: *pg_common
redis:
  jobs:
    common: &redis_common
      db: 0
      port: 6379
      host: <%= ENV["REDIS_HOST"] || "localhost" %>
      pool_size: 5
    development:
      <<: *redis_common
    test:
      <<: *redis_common
    production:
      <<: *redis_common
      pool_size: 10
